name: Deploy Web Previews
on:
  release:
    types: [published, edited, released]

jobs:
  Build-And-Deploy-Preview:
    runs-on: ubuntu-18.04
    steps:

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "${{ github.event.release.tag_name }}"

