name: Publish Release To Website
on:
  release:
    types: [published, edited]

jobs:
  Publish-Release-To-Website:
    runs-on: ubuntu-18.04
    env:
      publish_path: _news
      publish_branch: preview-dynamic-updates
    steps:

      - uses: CannonLock/build_release_page@master
        with:
          repository: ${{ github.repository }}
          release: ${{ github.event.release.tag_name }}

      - name: Setup SSH Keys and known_hosts
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HTCONDOR_WEB_DEPLOY_KEY }}

      - run: |
          mkdir website

          git clone git@github.com:htcondor/htcondor-web.git ./website

          mv ./*.md ./website/${{ env.publish_path }}

          cd website
          git checkout -b ${{ env.publish_branch }}
          git add .
          git config user.name "Automatic Release Publish"
          git config user.email ""
          git commit -am "GHA: htcondor/htcondor-web #$GITHUB_RUN_NUMBER"
          git push --set-upstream origin ${{ env.publish_branch }}
          git push



