name: Deploy Web Previews
on:
  release:
    types: [edited]

jobs:
  Build-And-Deploy-Preview:
    runs-on: ubuntu-18.04
    steps:

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

